Resources:
  CategoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "categoryName"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "categoryName"
          "KeyType": "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: "category"