Resources:
  ExpensesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "username"
          AttributeType: "S"
        - AttributeName: "expenseId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "username"
          KeyType: "HASH"
        - AttributeName: "expenseId"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: "expenses"