Resources:
  ExpenseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "expenseId"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "expenseId"
          "KeyType": "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: "expense"